import React, { Component } from 'react';

class TermsOfSerivce extends Component {

	render () {
		return (
			<div className="rich-text sm legal-line-height">
				<h4>License Agreement & Terms of Use</h4>
				<p>Easyset LLC, which includes the EasySet app, web interface, and database content (“EasySet”), provides its users (“clients”) with assessment tools and templates to facilitate physical security assessment tasks through a mobile application and web-based interface. Template content was developed by EasySet, is copyright protected, and based on years of professional experience and industry standard references. “EasySet Services” are limited to the following terms and conditions:</p>
				<ol className="numbered">
					<li><p>Each report template generated using EasySet is subject to the prescribed fees and applies to a single unique location, address and time as declared by the client. Copying, screenshots, photos, photocopy or any other means or attempts to duplicate any content produced as a result of using EasySet, without written consent from EasySet will be considered copyright and/or agreement infringement and will result in legal action by the laws of the state of California which govern this agreement.</p></li>
					<li><p>All content provided by EasySet is designed solely to assist the client, facilitate the completion, drafting, and production of a physical security assessment or applicable report.</p></li>
					<li><p>Although EasySet templates provide a wide array of options usually found throughout facilities and structures, EasySet cannot guarantee that all sections, areas, vulnerabilities and solutions are available for client selection. EasySet provides clients with some flexibility in order to address individual customer needs. However, EasySet LLC cannot guarantee that all conceivable options are available for selection.</p></li>
					<li><p>Vulnerability titles and content suggested by EasySet, serve only as a sample of total vulnerabilities suitable for the section or item. Selecting from the provided vulnerability list, although recommended, does not guarantee that all conceivable vulnerabilities for a specific section or area exist in the database for selection. Therefore, EasySet is by no means suggesting that if a vulnerability is not present in the checklist that such vulnerability or associated risk does not exist.</p></li>
					<li><p>Vulnerability descriptions provided by EasySet serve as an initial option for the customer's consideration and use. EasySet does not guarantee that the vulnerability is described in full, is applicable to the area(s) selected or to that specific location.  All vulnerabilities or content chosen by EasySet client(s) <strong>represent the client’s professional opinion only</strong>, based on the client’s assessment and does not represent any professional opinions of EasySet.</p></li>
					<li><p>EasySet provides its client(s) with various optional solutions for consideration. By providing these solutions, the client understands that the recommendations only represent a portion of the possible solutions available. The order of the solutions presented does not indicate any partiality or prioritization of any specific solution. The client understands although a solution might apply to one area , it does not necessarily apply to all.  Specific solutions may be unsuitable for certain vulnerabilities, and in some cases, may even cause potential harm if selected. Therefore, the solution suggestions are general and do not endorse any specific vulnerability. Solution descriptions and references are copyright protected by EasySet and provided to the client as a structured template designed to assist in compiling the client’s security assessment report.  EasySet does not mandate, endorse, or sanction any options presented, referenced as "solutions" or “solutions for consideration.” EasySet offers solutions understanding that the client will use and/or alter the wording and descriptions to his/her best judgment and takes full responsibility for any content rendered from EasySet. By using EasySet templates and content without editing, the client understands that he/she carefully read and agrees in full to all content provided and therefore chose to select the solution and description for his/her own use and responsibility. In most cases, EasySet provides references from reputable industry standard sources. Though EasySet tries its best to provide references to the client, it is the client’s sole responsibility to check each reference’s validity and applicability, choose whether or not to use it at his/her own risk, whether the client edited a solution or not. The reference chosen does not necessarily incorporate the entire solution selected and may refer to partial content only.</p></li>
					<li><p>The disclaimer included in the EasySet report template is provided to the client as a courtesy and does not substitute the client’s responsibility to seek legal advice before the download and release of a security assessment report to third-party beneficiaries (“Released Parties”). The client understands that EasySet cannot be held legally responsible for any content or lack of content in the provided legal disclaimer.</p></li>
					<li><p>Wording, phrasing, language, and grammar provided by EasySet is being done so to the best of its knowledge and after a courtesy review. All text within EasySet has no intention to offer judgment or insult to the assessed location, personnel, and assets. EasySet cannot be held responsible for any spelling, phrasing or grammar mistakes selected and used by the client. The client understands that it is his/her responsibility to conduct a complete review of all report content before download or distribution.</p></li>
					<li><p>EasySet provides its client(s) with the ability to upload, store and edit client and/or third-party beneficiaries (“Released Parties”) sensitive data from its designated servers. All data stored on the EasySet web application or servers is done so at the client's own risk. The client acknowledges that EasySet LLC recommends that all reports be completed as soon as possible followed by a permanent deletion from the EasySet servers. Storage of edited or completed reports on the EasySet servers is provided for thirty (30) days only after the report’s initial completion and download.  Once a report has been completed and downloaded, the client understands that he/she is limited to thirty days of editing, after which the report, will be deleted automatically, archived upon request and accessible with an additional retrieval fee.  EasySet assumes no responsibility for any draft or final report remaining on the client's account before, during or after it’s completion.</p></li>
					<li><p>EasySet services allow the client to enter data into the EasySet application which synchronizes in real-time with the EasySet web interface. Client agrees not to hold EasySet responsible for any technical faults which result in loss of data, photos, notes, or any other input by the client and /or loss of working hours or business reputation.</p></li>
					<li><p>The client confirms that he/she read, understands and agrees with all terms referenced in the EasySet privacy statement which specifies the collection, use, and storage of client data for purposes defined. The client understands that he/she will be notified of any changes to the terms and conditions. All information generated and/or stored on the EasySet servers is subject to the terms of the EasySet privacy statement.</p></li>
					<li><p>Although EasySet stores customer reports and information to the highest level of security standards, the client agrees not to hold EasySet liable for any claims, damages, losses or liabilities if any client, customer or Released Party information is breached due to unauthorized access to drafted,completed or archived reports or client data. The decision to maintain any drafted or completed report on an EasySet servers is based solely on the client's preference.</p></li>
					<li><p>The client agrees that any dispute, claim or controversy arising out of or relating to this agreement or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by arbitration in Los Angeles, CA before one arbitrator. The arbitration shall be administered by jams pursuant to its comprehensive arbitration rules and procedures [and in accordance with the expedited procedures in those rules] [or pursuant to jams' streamlined arbitration rules and procedures]. Judgment on the award may be entered in any court having jurisdiction. This clause shall not preclude parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction.</p></li>
					<li><p>The laws of the state of California (CA) govern this agreement (without giving effect to its conflicts of law principles). Both EasySet and its customer/client or any released party subjected to this agreement consent to the personal jurisdiction of the state and federal courts in Los Angeles County, CA.</p></li>
					<li><p>By using any of the EasySet services, the client states that he/she has active liability insurance which includes coverage of but is not limited to physical injury, harm, data breach, data loss, cybercrime, professional liability, errors, and omissions.</p></li>
					<li><p>The client confirms that he/she has legal ownership of all content uploaded or referenced by the client while using EasySet and has authorization from the relevant third party to collect potentially sensitive information about the facility in the form of text, photos, or otherwise.</p></li>
					<li><p>The client confirms that he/she understands that all sales are final. EasySet has a no return policy. However, in the case of a malfunction of the EasySet service, the customer may exchange the security assessment report for a new report.</p></li>
					<li><p>By clicking “Agree,” the client confirms that he/she read, fully understands the EasySet terms, conditions, and privacy statement and has the authority to represent his/her company  using the “EasySet services.”  By using any of the EasySet services, client accepts to RELEASE, WAIVE, DISCHARGE, HOLD HARMLESS and AGREE NOT TO SUE EasySet LLC, its officers, employees and/or agents from any claims, damages, loss, liabilities, lawsuits, actions, causes of action, claims for relief, demands, fees, expenses, and costs of any kind whatsoever, including attorney fees in perpetuity caused to client or any third party beneficiaries (“Released Parties”) including any loss arising from any claim of negligence against EasySet. The undersigned client also further hereby <strong>INDEMNIFIES</strong> EasySet and its agents, officers and employees from any loss, harm, liability, lawsuits, damages or costs, including court costs and attorney’s fees that EasySet may incur due to the client’s conduct or failure to adhere to the stated rules or the directions provided by EasySet.</p></li>
				</ol>

				<h4>Privacy Policy</h4>
				<p>EasySet LLC (EasySet) operates the www.easysetgo.com website, EasySet web interface, the EasySet App and its associated servers. The following privacy statement policy aims to inform EasySet users (clients) regarding the collection, use, and disclosure of personal and professional information through the use of Easyset Services. <strong>Absolutely, no client data collected while using any of the EasySet services is sold or shared with any third party.</strong></p>
				<p>By choosing to use any of the EasySet Services, the Client agrees to the collection and use of information subjected to policy, local, and Federal law.  Data collected by EasySet such as a user's email address and categorical/statistical assessment data will be used as described for statistical use to improve EasySet Services. Client’s personal information as well as any information related to the identity of the assessed (“Released party”) will be kept confidential and accessible by the client only. Easyset states that it has no access to identifying business information and will not transfer any of Client’s sensitive information to any third party without the client’s written consent. The terms used in this Privacy Policy are defined within EasySet's Terms and Conditions, accessible at www.easysetgo.com, unless otherwise specified in this policy.</p>
				
				<h5>Information Collection and Use:</h5>
				<p>For a better user experience, while using EasySet services, we may require the client to provide specific personally identifiable information, including but not limited to the client’s name, phone number, and postal address. This information collected will be used to contact the client, identify Client’s user, payments when applicable, and generating EasySet products/reports.</p>
				
				<h5>Log Data:</h5>
				<p>EasySet would like to inform the client that whenever the client visits an EasySet Service, we collect typical information that client’s browser sends to us referred to as Log Data. This Log Data may include information such as client’s computer’s Internet Protocol (“IP”) address, browser version, pages of our Service that client visits, the time and date of visit, the time spent on those pages, and other behavioral statistics. This data is protected using commercially acceptable means of doing so.</p>
				
				<h5>Cookies:</h5>
				<p>Most EasySet web-based services use "cookies," small text files that can be read by a web server in the domain that put the cookie on client’s hard drive. We may use cookies to store your preferences and settings; help to sign-in and analyze site operations to improve the user experience. Client has the option to either accept or refuse these cookies, and know when a cookie is being sent to his/her computer. Choosing to refuse our cookies, may impact portions of EasySet Services.</p>
				
				<h5>Service Providers:</h5>
				<p>We may employ third-party companies and individual’s due to the following reasons:</p>
				<ul>
					<li><p>To facilitate our Service</p></li>
					<li><p>To provide the Service on our behalf</p></li>
					<li><p>To perform Service-related services</p></li>
					<li><p>To assist EasySet in analyzing how the Service is used.</p></li>
				</ul>
				<p>We want to inform our EasySet clients/users that EasySet staff may have access to their  personal information only to perform the tasks assigned on our behalf. Regardless, they are legally obligated not to disclose or use the information for any other purpose.</p>

				<h5>Security:</h5>
				<p>We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.</p>

				<h6>Information we collect</h6>
				<ul>
					<li><p>Statistical means and application improvements</p></li>
					<li><p>Stats collected: Title (only) vulnerabilities used, titles (only) of Solutions for Consideration, Usage and Preference Information, assessment location zip codes (without specific locational info regarding client or third party assessed), IP address log, account creation info, device information and transaction info.</p></li>
				</ul>

				<h6>How we use info</h6>
				<ul>
					<li><p>To enhance the safety and security of our users and services</p></li>
					<li><p>For the customer support</p></li>
					<li><p>For research and development</p></li>
					<li><p>To enable communications to or between users</p></li>
					<li><p>To provide promotions</p></li>
					<li><p>In connection with legal proceedings if applicable</p></li>
				</ul>

				<h5>Links to Other Sites:</h5>
				<p>Our Service may contain links to other sites. Clicking on a third-party link, will direct client to that site. Note that these external sites are not operated by EasySet. Therefore, we strongly advise client to review the Privacy Policy of these websites. EasySet has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>

				<h5>Children’s Privacy:</h5>
				<p><strong>EasySet</strong> Services do not address anyone under the age of 18. We do not knowingly collect personal identifiable information from children under 18. In the case we discover that a child under 18 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.</p>

				<h5>Changes to This Privacy Policy:</h5>
				<p>We may update our Privacy Policy from time to time. Thus, we advise the client to review this page periodically for any changes. We will notify the client of any changes by posting the new Privacy Policy on this page. These changes are effective immediately, after they are posted on this page.</p>
			</div>
		);
	}
}

export default TermsOfSerivce;